package net.ghoula.melian.router

import net.ghoula.eru.Eru
import net.ghoula.eru.http.*
import net.ghoula.melian.RequestError

/** A single compiled route: path template, HTTP method, and the fully generated handler.
  *
  * The handler receives the raw request and path parameter values extracted by the trie. It
  * encapsulates the entire Girdle pipeline (extraction, decoding, validation, business logic,
  * response encoding) as a single closure generated by the router macro.
  */
final case class RouteEntry(
  pathTemplate: String,
  method: Method,
  handler: (Request[Body], Map[String, String]) => Eru[RequestError | HttpError, Response[Body]]
)
